name = "sport-performance-calculator"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[rules]]
type = "Text"
globs = ["**/*.html"]

[vars]
APP_NAME = "Sport Performance Calculator"

[[kv_namespaces]]
binding = "ATHLETE_KV"
id = "995fa4e894de4a44bfee75cdbdb97f0a"
